// Copyright 2024-2025 PowerServe Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "cmdline-sd.hpp"

#include "CLI/CLI.hpp"
#include "core/config.hpp"
#include "core/logger.hpp"

#include <filesystem>

namespace powerserve {

CommandLineArgumentSD parse_command_line_sd(const std::string_view program_name, int argc, char **argv) {
    CommandLineArgumentSD args;

    powerserve::print_timestamp();
    CLI::App app(program_name.data());

    app.add_option("--workfolder", args.work_folder, "Set the SD model folder path (required).")->required();
    app.add_option("--prompts", args.prompts, "Set the positive prompt (required).")->required();
    app.add_option("--nprompts", args.nprompts, "Set the negative prompt (optional).");
    app.add_option("-H,--height", args.height, "Set output image height (optional, default: 256).");
    app.add_option("-W,--width", args.width, "Set output image width (optional, default: 256).");
    app.add_option("-t,--thread", args.num_thread, "Set the number of threads (optional).");
    app.add_option("-b,--batch_size", args.batch_size, "Set the batch size (optional).");
    app.add_option(
        "--sample_method",
        args.sample_method,
        "Set sigma generation method (optional). Supported: "
        "[discrete, karras, exponential, sgm_uniform, simple, smoothstep, kl_optimal, lcm, bong_tangent]. "
        "Default when omitted: discrete."
    );
    app.add_option("--dump-embeddings", args.dump_embeddings, "Dump text encoder embeddings to this file (optional).");
    app.add_option(
        "--compare-embeddings",
        args.compare_embeddings,
        "Compare against a reference embedding dump generated by another run (optional)."
    );
    app.add_option(
        "--compare-max-abs-threshold",
        args.compare_max_abs_threshold,
        "Fail if max_abs_error exceeds this value; <= 0 disables the check."
    );
    app.add_option(
        "--compare-rmse-threshold",
        args.compare_rmse_threshold,
        "Fail if RMSE exceeds this value; <= 0 disables the check."
    );
    app.add_option("--clip-skip", args.clip_skip, "Override clip_skip in text encoder; <= 0 keeps model default.");
    app.add_option(
        "--latent-bin",
        args.latent_bin,
        "Input latent bin path for VAE decode (float32 raw, [W/8,H/8,16,1])."
    );
    app.add_option(
        "--vae-compare-dir",
        args.vae_compare_dir,
        "Output directory for VAE compare artifacts (run_sd_latent_vae.png + powerserve_decoded.bin). "
        "Default: workfolder."
    );

    try {
        app.parse(argc, argv);
    } catch (const CLI::ParseError &err) {
        const int ret = app.exit(err);
        exit(ret);
    }

    return args;
}

SDConfig get_config_from_argument_sd(const CommandLineArgumentSD &args) {
    Path model_config_path;
    const Path work_folder_path(args.work_folder);

    if (std::filesystem::is_directory(work_folder_path)) {
        model_config_path = work_folder_path / MODEL_CONFIG_FILENAME;
    } else {
        model_config_path = work_folder_path;
    }

    SDConfig config(model_config_path);
    auto &hyper_params = config.hyper_params;

    if (args.num_thread != 0) {
        hyper_params.n_threads = args.num_thread;
    }

    if (args.batch_size != 0) {
        hyper_params.batch_size = args.batch_size;
    }

    if (args.sample_method.empty()) {
        hyper_params.sample_method = "discrete";
    } else {
        hyper_params.sample_method = args.sample_method;
    }

    if (args.clip_skip > 0) {
        config.text_encode_config.clip_skip = args.clip_skip;
    }

    hyper_params.height = args.height;
    hyper_params.width  = args.width;
    hyper_params.prompt = args.prompts;
    hyper_params.negative_prompt = args.nprompts;

    return config;
}

} // namespace powerserve
